version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: golfclub_db
      MYSQL_USER: Qap2
      MYSQL_PASSWORD: 1214
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  golfclub-api:
    build:
      context: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/golfclub_db
      SPRING_DATASOURCE_USERNAME: Qap2
      SPRING_DATASOURCE_PASSWORD: 1214

volumes:
  mysql-data:
